const int ORDER_PLACED = 51;
const int ORDER_ACCEPTED = 52;
const int SENDER_APPROVED_COURIER_DEPARTURE = 53;
const int TESTER_APPROVED_COURIER_ARRIVAL = 54;
const int SPECIMEN_EDITED = 55;
const int ADD_OR_UPDATE_ORDER = 56;
const int DELETE_ORDER = 57;