const int PLACE_ORDER = 1;
const int COURIER_ACCEPT_ORDER = 2;
const int COURIER_NOTIFY_ARRIVAL_SENDER = 3;
const int SENDER_APPROVE_COURIER_ARRIVAL = 4;
const int COURIER_NOTIFY_ARRIVAL_TESTER = 5;
const int TESTER_APPROVE_COURIER_ARRIVAL = 6;
const int TESTER_ADD_TEST_RESULT = 7;