const int PLACE_ORDER = 1;
const int COURIER_ACCEPT_ORDER = 2;
const int COURIER_NOTIFY_ARRIVAL_SENDER = 3;
const int SENDER_APPROVE_COURIER_ARRIVAL = 4;
const int COURIER_NOTIFY_ARRIVAL_TESTER = 5;
const int TESTER_APPROVE_COURIER_ARRIVAL = 6;
const int TESTER_ADD_TEST_RESULT = 7;

const int ADD_ORDER = 8;
const int EDIT_SHIPMENT_INFO = 9;
const int EDIT_PATIENT_INFO = 10;
const int DELETE_PATIENT = 11;
const int ADD_PATIENT = 12;
const int DELETE_ORDER = 13;
const int EDIT_SPECIMEN_FEEDBACK = 14;
const int EDIT_TEST_RESULT = 15;

const int SEND_SMS_TO_LISTENER = 16;
const int SEND_NOTIFICATION_SMS = 17;

const int COURIER_NOTIFY_ARRIVAL_REFERRER = 18;
